worker_processes  1;

events {
    worker_connections  1024;
}

http {
    client_max_body_size 210M;
    upstream spring_cluster {
        server 127.0.0.1:8081;
        server 127.0.0.1:8082;
    }

    server {
        listen 8080;

        location / {
            proxy_set_header Host localhost;
            proxy_set_header X-Forwarded-For $remote_addr;

            proxy_pass http://spring_cluster;
        }
    }
}

